apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: awseks-frontend
  namespace: argocd
spec:
  project: default
  source:
    # 인프라 GitHub 리포지토리 주소
    repoURL: 'https://github.com/seoyeon020/aws_eks_infra.git'
    targetRevision: HEAD
    # 리포지토리 내의 매니페스트 파일 경로 (루트 폴더일 경우 '.')
    path: 'manifests/frontend'
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true